services:
  # Next.js 应用服务
  next-blog:
    build:
      context: .
      dockerfile: dockerfile
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    networks:
      - blog-network
    platform: "linux/amd64"
    image: crpi-lgty92ojoeq0mwd1.cn-hangzhou.personal.cr.aliyuncs.com/next-blog/next-blog:amd64
  # Nginx 反向代理服务
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./public:/var/www/blog-fe:ro
      - /www/yoursigh.top/ssl:/www/yoursigh.top/ssl:ro
    depends_on:
      - next-blog
    restart: unless-stopped
    networks:
      - blog-network

networks:
  blog-network:
    driver: bridge
